---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gotk-monitoring
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h0m0s
  path: ./manifests/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-monitoring
  healthChecks:
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  - kind: Deployment
    name: grafana
    namespace: flux-system
