---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h
  path: ./metallb-system
  prune: true
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client