---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rpi-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: rpi-infra
  timeout: 20s
  url: ssh://git@github.com/sthlmio/rpi-infra
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rpi-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: rpi-apps
  timeout: 20s
  url: ssh://git@github.com/sthlmio/rpi-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  - kind: Deployment
    name: grafana
    namespace: flux-system
  interval: 1h0m0s
  path: ./manifests/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rpi-infra
  namespace: flux-system
spec:
  interval: 1h
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rpi-apps
  namespace: flux-system
spec:
  interval: 6h
  dependsOn:
    - name: rpi-infra
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-apps
  validation: client
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: web-update
  namespace: flux-system
spec:
  interval: 5m
  checkout:
    branch: main
    gitRepositoryRef:
      name: rpi-apps
  update:
    strategy: Setters
  commit:
    authorName: fluxcdbot
    authorEmail: fluxcdbot@users.noreply.github.com
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: sthlmio-web
  namespace: flux-system
spec:
  interval: 5m
  image: sthlmio/web
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: sthlmio-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sthlmio-web
  policy:
    semver:
      range: 1.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: sthlmio-faas-web-mail
  namespace: flux-system
spec:
  interval: 5m
  image: sthlmio/faas-web-mail
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: sthlmio-faas-web-mail
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sthlmio-faas-web-mail
  policy:
    semver:
      range: 1.0.x