---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB7V0dqR+d8S3fsZsr0L0+PIf1vSQwOYZrjEMU0elWYC0CrQ6AgxE3yTFpXyXq+YFSXQ62oLgYHZYeLLB0PXl77Vwb6SglV5KYMg6Q+9OmZJVTZruo1zCLAGoLywZwqzwxrLJK7PZENk2H5HV4dtonXtQXBdnp+lninAPpjdYr4J3Sbtzrg8Sy+oG9zTgYturNb6LSg7/EnKclrRScfnWUeN0E6UhjPnUF7hOrLfF9vT+paF64P+zrU3/sZQJ2+QZvXKEdqTWAdDysXdbExPOQOT8nLOUq/u7Ot8p8twk7Z4Cd+FMTTls87GZGsdaFgW0JOU/Sy46zMhtlSuDanQPGQn4MugpzN90SmBuLAcy6LGURhEdgqWYmav/rQtWS3Vw/HCUWz0s2RpsmAfI3UcbmPgo9+fJFSCjYUbtR56rC/RwOrzNN/OJILea2fub2UM2+HUNbVueiVh8WvHtSfpCAQi9/1OFUVijfVg6VyBEWN6iFc/UT92sJGLIiWYx2jhz8DL4Qme8Jp852f0JujlHGwsf7ZvrGxzcn29Z42HlIO9UBdrOx8YUUSp75NM8z1UE3o2b2isj9gDlgQKpWuBDvk6yPy8Bx8gq2xNmIl00ATxToNDV3PmqSl0P+mALe4ghaz4Y00bmpV9YcqjEbNjrbAjsV1FvN5kvNDh8rfSxkTXszBhvsK/SYybX+mbWi2+8JhV0XLjQ87JyWnOEoT26jr0AW8Bl/YK/fGBqorsL1hAk/GGLwy0tLwU9wklNtTMgkzORDq0WLVOQ1pRewjjfAbx2JGaHCmK3DRBrM5JAlq
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
