---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h
  path: ./kube-system/kube-vip
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client