---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: node-local-dns
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h
  path: ./kube-system/node-local-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: node-local-dns
      namespace: kube-system