---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h
  path: ./traefik
  prune: true
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik