---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1h
  path: ./linkerd
  prune: true
  dependsOn:
    - name: cert-manager
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client