---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: openfaas
  namespace: flux-system
spec:
  timeout: 30s
  interval: 1h
  path: ./openfaas
  prune: true
  dependsOn:
    - name: cert-manager
    - name: sealed-secrets
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #     kind: HelmRelease
  #     name: openfaas
  #     namespace: openfaas