---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 1h
  path: ./contour
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: contour
      namespace: contour