---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  interval: 1h
  path: ./linkerd-viz
  prune: true
  dependsOn:
    - name: linkerd
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client