# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: monitoring
#   namespace: flux-system
# spec:
#   timeout: 5m0s
#   interval: 1h
#   path: ./monitoring
#   prune: true
#   dependsOn:
#     - name: sealed-secrets
#   sourceRef:
#     kind: GitRepository
#     name: rpi-infra
#   validation: client
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: prometheus
#       namespace: monitoring
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: grafana
#       namespace: monitoring