---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  path: ./kube-system/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: sealed-secrets-controller
      namespace: kube-system