---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: apps-sthlmio-web-update
  namespace: flux-system
spec:
  interval: 1m0s
  update:
    path: ./sthlmio/web
    strategy: Setters
  sourceRef:
    kind: GitRepository
    name: rpi-apps
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com