---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: sthlmio-web
  namespace: flux-system
spec:
  interval: 1m
  image: sthlmio/web
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: sthlmio-faas-web-mail
  namespace: flux-system
spec:
  interval: 1m
  image: sthlmio/faas-web-mail