---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: etcd
  namespace: flux-system
spec:
  interval: 1h
  path: ./kube-system/etcd
  prune: true
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: rpi-infra
  validation: client